const data=

    [
        { key:1,
          qid: "2",
          question:'What is the highest level of education you have completed ?',
          opone: 'Illiterate / No Education',
          optwo: 'Primary Level',
          opthree: 'Secondary Level',
          opfour: 'Undergraduate Degree',
          opfive: "Masters Degree",  
          opsix: 'PhD Degree', 
          valone: 1,
          valtwo: 4,
          valthree: 5,
          valfour: 0,
          valfive: 2,
          valsix: 3,
        },
        { key:2,
            qid: "3", 
            question:'What is your occupation ?',
            opone: 'Unemployed',
            optwo: 'Laborer',
            opthree: 'Academia/Defence/Police',
            opfour: 'Technology/Design/IT',
            opfive: 'Freelance/Self-employed',
            opsix: 'Other Private/Govt',
            valone: 5,
            valtwo: 1,
            valthree: 4,
            valfour: 0,
            valfive: 3,
            valsix: 2,
        },
        { key:3,
            qid: "4",
            question:'What is your area of residence ?',
            opone: 'Rural',
            optwo: 'Urban',
            opthree: 'Hilly/ Forest region',
            valone: 1,
            valtwo: 2,
            valthree: 0,
        },
        { key:4,
            qid: "5",
            question:'For how long (duration) have you suffered from diabetes ?',
            opone: 'Less than 10 yrs',
            optwo: '10-15 yrs',
            opthree: '15-20 yrs',
            opfour: 'More than 20 yrs',
            valone: 2,
            valtwo: 0,
            valthree: 1,
            valfour: 3,
        },
        { key:5,
            qid: "6",
            question:'What is the type of footwear you mostly wear ?',
            opone: 'High heeled shoes',
            optwo: 'Open toe shoes',
            opthree: 'Laced shoes',
            opfour: 'Special shoes',
            opfive: 'Sandals',
            valone: 0,
            valtwo: 2,
            valthree: 1,
            valfour: 4,
            valfive: 3,
        },
        { key:6,
            qid: "7",
            question:'What type of foot condition do you have ?',
            opone: 'Trauma',
            optwo: 'Bony Prominence',
            opthree: 'Sensory disturbances',
            opfour: 'Heel pain',
            opfive: 'Foot ulcer',
            opsix: 'Atrophy of the skin',  
            valone: 5,
            valtwo: 1,
            valthree: 4,
            valfour: 3,
            valfive: 2,
            valsix: 0, 
        },
        { key:7,
            qid: "8",
            question:'What comorbidities have you faced with diabetes ?',
            opone: 'Coronary artery disease',
            optwo: 'Myocardial infarction',
            opthree: 'Diabetic strokes',
            opfour: 'Congestive heart failure',
            opfive: 'None',
            valone: 1,
            valtwo: 2,
            valthree: 4,
            valfour: 0,
            valfive: 3,
               
        },
        { key:8,
            qid: "9",
            question:'Where do you have a swelling ?',
            opone: 'Ankle',
            optwo: 'Whole Foot',
            opthree: 'Specific Area',
            valone: 0,
            valtwo: 2,
            valthree: 1,   
        },
        { key:9,
            qid: "10",
            question:'What is the approximate ankle movement on your feet ?',
            opone: '0-20 degrees',
            optwo: '0-35 degree',
            opthree: '0-50 degree',
            opfour: '0-75 degree', 
            valone: 0,
            valtwo: 1,
            valthree: 2,
            valfour: 3, 
        },
        { key:10,
            qid: "11",
            question:'What kind of foot deformities do you suffer from ?',
            opone: 'Skin ulcer',
            optwo: 'Callus and Pressure Sores',
            opthree: 'Infection',
            opfour: 'Cosmetic allergy', 
            valone: 3,
            valtwo: 2,
            valthree: 1,
            valfour: 0, 
        },
        { key:11,
            qid: "12",
            question:'What is the major cause for change in hormone levels ?',
            opone: 'Stress/Depression',
            optwo: 'Menstruation',
            opthree: 'Menopause',
            opfour: 'None',  
            valone: 3,
            valtwo: 1,
            valthree: 0,
            valfour: 2,
        },
        { key:12,
            qid: "13",
            question:'At what section of the foot do you feel pain ?',
            opone: 'Forefoot',
            optwo: 'Midfoot',
            opthree: 'Lateral Foot',
            valone: 0,
            valtwo: 2,
            valthree: 1,  
        },
        { key:13,
            qid: "1",
            question:'Choose your Gender',
            opone: 'Female',
            optwo: 'Male', 
            valone: 0,
            valtwo: 1, 
        },

    ];

export default data;