const data=

    [
        { key:1,
          qid: "1",
          question:'What is the highest level of education you have completed ?',
          opone: 'Illiterate / No Education',
          optwo: 'Primary Level',
          opthree: 'Secondary Level',
          opfour: 'Undergraduate Degree',
          opfive: 'Graduate Degree',  
        },
        { key:2,
            qid: "2", 
            question:'What is your occupation ?',
            opone: 'Unemployed',
            optwo: 'Laborer',
            opthree: 'Academia/Defence/Government',
            opfour: 'Technology/Design/IT',
            opfive: 'Freelance/Self-employed',
        },
        { key:3,
            qid: "3",
            question:'What is your area of residence ?',
            opone: 'Rural',
            optwo: 'Urban',
            opthree: 'Hilly/ Forest region',
        },
        { key:4,
            qid: "4",
            question:'For how long (duration) have you suffered from diabetes ?',
            opone: 'Less than 10 yrs',
            optwo: '10-15 yrs',
            opthree: '15-20 yrs',
            opfour: 'More than 20 yrs',
        },
        { key:5,
            qid: "5",
            question:'What is the type of footwear you mostly wear ?',
            opone: 'High heeled shoes',
            optwo: 'Open toe shoes',
            opthree: 'Laced shoes',
            opfour: 'Special shoes',
            opfive: 'Sandals',
        },
        { key:6,
            qid: "6",
            question:'What type of foot condition do you have ?',
            opone: 'Trauma',
            optwo: 'Bony Prominence',
            opthree: 'Sensory disturbances',
            opfour: 'Heel pain',
            opfive: 'Foot ulcer',
            opsix: 'Atrophy of the skin',   
        },
        { key:7,
            qid: "7",
            question:'What comorbidities have you faced with diabetes ?',
            opone: 'Coronary artery disease',
            optwo: 'Myocardial infarction',
            opthree: 'Diabetic strokes',
            opfour: 'Congestive heart failure',
            opfive: 'Peripheral vascular disease',
               
        },
        { key:8,
            qid: "8",
            question:'Where do you have a swelling ?',
            opone: 'Ankle',
            optwo: 'Whole Foot',
            opthree: 'Specific Area',   
        },
        { key:9,
            qid: "9",
            question:'What is the approximate ankle movement on your feet ?',
            opone: '0-20 degrees',
            optwo: '0-35 degree',
            opthree: '0-50 degree',
            opfour: '0-75 degree',  
        },
        { key:10,
            qid: "10",
            question:'What kind of foot deformities do you suffer from ?',
            opone: 'Skin ulcer',
            optwo: 'Callus and Pressure Sores',
            opthree: 'Infection',
            opfour: 'Cosmetic allergy',  
        },
        { key:11,
            qid: "11",
            question:'What is the major cause for change in hormone levels ?',
            opone: 'Stress/Depression',
            optwo: 'Menstruation',
            opthree: 'Menopause',  
        },
        { key:12,
            qid: "12",
            question:'At what section of the foot do you feel pain ?',
            opone: 'Forefoot',
            optwo: 'Midfoot',
            opthree: 'Lateral Foot',  
        },

    ];

export default data;